### ISSUE TITLE
Have Everyone Contribute

### ISSUE THREAD

**Issue by Abnormal-Jester** [Abnormal-Jester/OaktonChess#1]
- ~~Adam El Sheikh~~
- Davin Um _Need to find/make github account_
- Grace Yu @shrockers 
- Zhiyu Zhu @ApolloZhu

**Comment by Abnormal-Jester** [comment]
- ~~Adam El Sheikh~~
- ~~Davin Um~~
- ~~Grace Yu~~
- ~~Zhiyu Zhu~~
- Angela Xu _Unknown Account_

**Comment by ApolloZhu** [comment]
It’s unlikely that we’ll continue to work on this project in the future, could you please close all issues and archive this repo? @jarett-lee 

Thanks :heart:
